version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: energy_nexus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energy_nexus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: energy_nexus_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: energy_nexus_backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: energy_nexus_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  pgdata:
